[theme]
primaryColor = "#10b981"
backgroundColor = "#0b152bff"
secondaryBackgroundColor = "#090924ff"
textColor = "#e2e8f0"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "warning"

[server]
headless = true
port = 8502
